In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sb

In [3]:
# Read dataset
df = pd.read_csv("/Users/remmy/Documents/Projects/Data-Science/SEM 3/Data Minning, Modeling and Analytics/Pokemon.csv")

In [4]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [5]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [6]:
sorted_dataset = df['Total'].sort_index(ascending=False)

print(sorted_dataset)

799    600
798    680
797    600
796    700
795    600
      ...
4      309
3      625
2      525
1      405
0      318
Name: Total, Length: 800, dtype: int64

In [7]:
sorted_by_total = df.sort_values(by='Total', ascending=False)

print(sorted_by_total)

       #                   Name   Type 1    Type 2  Total   HP  Attack  \
426  384  RayquazaMega Rayquaza   Dragon    Flying    780  105     180
164  150    MewtwoMega Mewtwo Y  Psychic       NaN    780  106     150
163  150    MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190
422  382    KyogrePrimal Kyogre    Water       NaN    770  100     150
424  383  GroudonPrimal Groudon   Ground      Fire    770  100     180
..   ...                    ...      ...       ...    ...  ...     ...
13    10               Caterpie      Bug       NaN    195   45      30
288  265                Wurmple      Bug       NaN    195   45      45
446  401              Kricketot      Bug       NaN    194   37      25
322  298                Azurill   Normal     Fairy    190   50      20
206  191                Sunkern    Grass       NaN    180   30      30

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
426      100      180      100    115           3       True
164       70      194      120    140           1       True
163      100      154      100    130           1       True
422       90      180      160     90           3       True
424      160      150       90     90           3       True
..       ...      ...      ...    ...         ...        ...
13        35       20       20     45           1      False
288       35       20       30     20           3      False
446       41       25       41     25           4      False
322       40       20       40     20           3      False
206       30       30       30     30           2      False

[800 rows x 13 columns]

In [8]:
sum_of_toal = df['Total'].sum()

print(sum_of_toal)

348082

In [9]:
total_by_name = df.groupby('Name')['Total'].sum()

print(total_by_name)

Name
Abomasnow                  494
AbomasnowMega Abomasnow    594
Abra                       310
Absol                      465
AbsolMega Absol            565
                          ...
Zoroark                    510
Zorua                      330
Zubat                      245
Zweilous                   420
Zygarde50% Forme           600
Name: Total, Length: 800, dtype: int64

In [10]:
total_by_name

Name
Abomasnow                  494
AbomasnowMega Abomasnow    594
Abra                       310
Absol                      465
AbsolMega Absol            565
                          ...
Zoroark                    510
Zorua                      330
Zubat                      245
Zweilous                   420
Zygarde50% Forme           600
Name: Total, Length: 800, dtype: int64

In [11]:
total_by_attack = df.groupby('Attack')['Total'].sum()

print(total_by_attack)

Attack
5       670
10     1245
15      200
20     2060
22      213
       ...
165    1668
170    1400
180    2150
185     600
190     780
Name: Total, Length: 111, dtype: int64

In [ ]:
null_values = df.isnull()

print(null_values)

         #   Name  Type 1  Type 2  Total     HP  Attack  Defense  Sp. Atk  \
0    False  False   False   False  False  False   False    False    False
1    False  False   False   False  False  False   False    False    False
2    False  False   False   False  False  False   False    False    False
3    False  False   False   False  False  False   False    False    False
4    False  False   False    True  False  False   False    False    False
..     ...    ...     ...     ...    ...    ...     ...      ...      ...
795  False  False   False   False  False  False   False    False    False
796  False  False   False   False  False  False   False    False    False
797  False  False   False   False  False  False   False    False    False
798  False  False   False   False  False  False   False    False    False
799  False  False   False   False  False  False   False    False    False

     Sp. Def  Speed  Generation  Legendary
0      False  False       False      False
1      False  False       False      False
2      False  False       False      False
3      False  False       False      False
4      False  False       False      False
..       ...    ...         ...        ...
795    False  False       False      False
796    False  False       False      False
797    False  False       False      False
798    False  False       False      False
799    False  False       False      False

[800 rows x 13 columns]

In [13]:
number_of_null_values = df.isnull().sum()

print(number_of_null_values)

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64